disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - identifier_name
  - for_where
  - unused_closure_parameter
  - trailing_comma
included:
  - MinimalMIDIPlayer
