language: objective-c
xcode_project: "Framework/MIKMIDI.xcodeproj"

osx_image: xcode7.1

xcode_scheme: 
    - MIKMIDI
    - MIKMIDI-iOS
xcode_sdk:
    - macosx
    - iphonesimulator

matrix:
    exclude:
        - xcode_scheme: MIKMIDI
          xcode_sdk: iphonesimulator
        - xcode_scheme: MIKMIDI-iOS
          xcode_sdk: macosx
        